"""Fix game model player_o column name

Revision ID: 53971649b0c3
Revises: 5c86a8b43e04
Create Date: 2021-02-12 00:03:57.527349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53971649b0c3'
down_revision = '5c86a8b43e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_o', sa.Integer(), nullable=True))
        batch_op.drop_constraint('game_player_y_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'player', ['player_o'], ['id'])
        batch_op.drop_column('player_y')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_y', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('game_player_y_fkey', 'player', ['player_y'], ['id'])
        batch_op.drop_column('player_o')

    # ### end Alembic commands ###
