"""Add game model

Revision ID: 5c86a8b43e04
Revises: 01bca61f9559
Create Date: 2021-02-11 23:44:37.443793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c86a8b43e04'
down_revision = '01bca61f9559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_x', sa.Integer(), nullable=True),
    sa.Column('player_y', sa.Integer(), nullable=True),
    sa.Column('board', sa.String(length=9), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('loser', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loser'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_x'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_y'], ['player.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
